language: node_js
dist: trusty
sudo: required
node_js: v8.16.1
addons:
  apt:
    packages:
    - libudev-dev
services:
  - docker
install:
  - npm install
  - make build-dapp
  - make build-app
script:
  - make cliquebait-start
  - sleep 10
  - make test-dapp
  - make cliquebait-stop
deploy:
  provider: pages
  local-dir: ./dist/
  email: deploy@travis-ci.com
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
