language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install
  - make build-dapp
  - make build-app
script:
  - make cliquebait-start
  - sleep 10
  - npm -s test-dapp
  - make cliquebait-stop
