language: node_js
dist: trusty
sudo: required
node_js: v8.16.1
addons:
  apt:
    packages:
    - libudev-dev
services:
  - docker
env:
  - RELAYABLE_NFT=0x4a70091a675f2c0fae14a5f229345d6b62f932ea
  - GA_TRACKING_ID=G-WN45MV635H
install:
  - npm install
  - make build-dapp
  - make build-app
script:
  - make cliquebait-start
  - sleep 10
  - make test-dapp
  - make cliquebait-stop
  - make bundle
deploy:
  provider: pages
  local-dir: ./dist/
  email: deploy@travis-ci.com
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
