language: node_js
dist: trusty
sudo: required
node_js: v8.16.1
addons:
  apt:
    packages:
    - libudev-dev
env:
  - URL=https://f-o-a-m.github.io/foam.lite
services:
  - docker
install:
  - npm install
  - make build-dapp
  - make build-app
script:
  - make cliquebait-start
  - sleep 10
  - make test-dapp
  - make cliquebait-stop
  - cp -v .deployed-contracts/*.json build/
  - make bundle
deploy:
  provider: pages
  local-dir: ./dist/
  email: deploy@travis-ci.com
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
